import type { Metadata } from "next";
import { Alata } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner"
import Header from "@/components/header";

const alata = Alata({
  variable: "--font-alata",
  subsets: ["vietnamese"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${alata.variable} antialiased`}
      >
        <Toaster />
        <div className="overflow-hidden">
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
